-- 17_aturan_inventory.sql

-- Add expiry_date to products
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS expiry_date date;

-- Create inventory_adjustments table
CREATE TABLE IF NOT EXISTS public.inventory_adjustments (
    id bigint generated by default as identity primary key,
    store_id uuid not null references public.stores(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    qty_before numeric not null,
    qty_adjusted numeric not null,
    qty_after numeric not null,
    reason text not null,
    note text,
    cashier_name text,
    created_at timestamp with time zone default now() not null
);

-- Create stock_ledgers table
CREATE TABLE IF NOT EXISTS public.stock_ledgers (
    id bigint generated by default as identity primary key,
    store_id uuid not null references public.stores(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    reference_type text not null,
    reference_id text,
    qty_changed numeric not null,
    balance_stock numeric not null,
    cashier_name text,
    created_at timestamp with time zone default now() not null
);

-- RLS
ALTER TABLE public.inventory_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_ledgers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_inventory_adjustments" ON public.inventory_adjustments
  FOR ALL
  USING (store_id IN (SELECT public.my_store_ids()))
  WITH CHECK (store_id IN (SELECT public.my_store_ids()));

CREATE POLICY "tenant_stock_ledgers" ON public.stock_ledgers
  FOR ALL
  USING (store_id IN (SELECT public.my_store_ids()))
  WITH CHECK (store_id IN (SELECT public.my_store_ids()));

-- Recreate decrement_stock with ledger
DROP FUNCTION IF EXISTS public.decrement_stock(BIGINT, NUMERIC);
CREATE OR REPLACE FUNCTION public.decrement_stock(
  p_product_id BIGINT, 
  p_qty NUMERIC,
  p_ref_type TEXT DEFAULT 'sale',
  p_ref_id TEXT DEFAULT NULL,
  p_cashier TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  v_store_id uuid;
  v_balance numeric;
BEGIN
  IF p_qty <= 0 THEN
    RAISE EXCEPTION 'qty must be positive';
  END IF;
  
  UPDATE public.products
  SET stock = stock - p_qty
  WHERE id = p_product_id
    AND store_id IN (SELECT public.my_store_ids())
  RETURNING store_id, stock INTO v_store_id, v_balance;

  IF FOUND THEN
    INSERT INTO public.stock_ledgers (store_id, product_id, reference_type, reference_id, qty_changed, balance_stock, cashier_name)
    VALUES (v_store_id, p_product_id, p_ref_type, p_ref_id, -p_qty, v_balance, p_cashier);
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.decrement_stock TO authenticated;

-- Recreate increment_stock with ledger
DROP FUNCTION IF EXISTS public.increment_stock(BIGINT, NUMERIC);
CREATE OR REPLACE FUNCTION public.increment_stock(
  p_product_id BIGINT, 
  p_qty NUMERIC,
  p_ref_type TEXT DEFAULT 'return',
  p_ref_id TEXT DEFAULT NULL,
  p_cashier TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  v_store_id uuid;
  v_balance numeric;
BEGIN
  IF p_qty <= 0 THEN
    RAISE EXCEPTION 'qty must be positive';
  END IF;
  
  UPDATE public.products
  SET stock = stock + p_qty
  WHERE id = p_product_id
    AND store_id IN (SELECT public.my_store_ids())
  RETURNING store_id, stock INTO v_store_id, v_balance;

  IF FOUND THEN
    INSERT INTO public.stock_ledgers (store_id, product_id, reference_type, reference_id, qty_changed, balance_stock, cashier_name)
    VALUES (v_store_id, p_product_id, p_ref_type, p_ref_id, p_qty, v_balance, p_cashier);
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.increment_stock TO authenticated;

-- adjust_stock RPC for manual adjustment and opname
CREATE OR REPLACE FUNCTION public.adjust_stock(
  p_product_id BIGINT, 
  p_qty_adjusted NUMERIC,
  p_reason TEXT,
  p_note TEXT,
  p_cashier TEXT,
  p_ref_type TEXT DEFAULT 'adjustment'
)
RETURNS VOID
LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  v_store_id uuid;
  v_qty_before numeric;
  v_qty_after numeric;
BEGIN
  -- get current
  SELECT store_id, stock INTO v_store_id, v_qty_before
  FROM public.products
  WHERE id = p_product_id AND store_id IN (SELECT public.my_store_ids())
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Product not found or access denied';
  END IF;

  v_qty_after := v_qty_before + p_qty_adjusted;

  -- update product
  UPDATE public.products
  SET stock = v_qty_after
  WHERE id = p_product_id;

  -- record to inventory_adjustments
  INSERT INTO public.inventory_adjustments (store_id, product_id, qty_before, qty_adjusted, qty_after, reason, note, cashier_name)
  VALUES (v_store_id, p_product_id, v_qty_before, p_qty_adjusted, v_qty_after, p_reason, p_note, p_cashier);

  -- record to stock_ledgers
  INSERT INTO public.stock_ledgers (store_id, product_id, reference_type, reference_id, qty_changed, balance_stock, cashier_name)
  VALUES (v_store_id, p_product_id, p_ref_type, NULL, p_qty_adjusted, v_qty_after, p_cashier);
END;
$$;
GRANT EXECUTE ON FUNCTION public.adjust_stock TO authenticated;
